version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: abiza-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
